{"ast":null,"code":"var _jsxFileName = \"C:\\\\Users\\\\a.sutic\\\\React\\\\clothing\\\\client\\\\src\\\\components\\\\error-boundary\\\\error-boundary.component.jsx\";\nimport React, { Component } from \"react\";\nexport default class ErrorBoundary extends Component {\n  constructor() {\n    super();\n    this.state = {\n      hasError: false\n    };\n  } // if children through an error that error is passed into this function\n\n\n  static getDerivedStateFromError(error) {\n    // process error\n    return {\n      hasError: true\n    };\n  }\n\n  componentDidCatch(error, info) {\n    console.log(error);\n  }\n\n  render() {\n    if (this.state.hasError) {\n      return React.createElement(\"div\", {\n        __source: {\n          fileName: _jsxFileName,\n          lineNumber: 23\n        },\n        __self: this\n      }, \"Something went wrong\");\n    }\n\n    return this.props.children;\n  }\n\n}","map":{"version":3,"sources":["C:\\Users\\a.sutic\\React\\clothing\\client\\src\\components\\error-boundary\\error-boundary.component.jsx"],"names":["React","Component","ErrorBoundary","constructor","state","hasError","getDerivedStateFromError","error","componentDidCatch","info","console","log","render","props","children"],"mappings":";AAAA,OAAOA,KAAP,IAAgBC,SAAhB,QAAiC,OAAjC;AAEA,eAAe,MAAMC,aAAN,SAA4BD,SAA5B,CAAsC;AACnDE,EAAAA,WAAW,GAAG;AACZ;AACA,SAAKC,KAAL,GAAa;AACXC,MAAAA,QAAQ,EAAE;AADC,KAAb;AAGD,GANkD,CAQnD;;;AACA,SAAOC,wBAAP,CAAgCC,KAAhC,EAAuC;AACrC;AACA,WAAO;AAAEF,MAAAA,QAAQ,EAAE;AAAZ,KAAP;AACD;;AAEDG,EAAAA,iBAAiB,CAACD,KAAD,EAAQE,IAAR,EAAc;AAC7BC,IAAAA,OAAO,CAACC,GAAR,CAAYJ,KAAZ;AACD;;AAEDK,EAAAA,MAAM,GAAG;AACL,QAAG,KAAKR,KAAL,CAAWC,QAAd,EAAwB;AACpB,aAAO;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,gCAAP;AACH;;AAED,WAAO,KAAKQ,KAAL,CAAWC,QAAlB;AACH;;AAxBkD","sourcesContent":["import React, { Component } from \"react\";\r\n\r\nexport default class ErrorBoundary extends Component {\r\n  constructor() {\r\n    super();\r\n    this.state = {\r\n      hasError: false\r\n    };\r\n  }\r\n\r\n  // if children through an error that error is passed into this function\r\n  static getDerivedStateFromError(error) {\r\n    // process error\r\n    return { hasError: true };\r\n  }\r\n\r\n  componentDidCatch(error, info) {\r\n    console.log(error);\r\n  }\r\n\r\n  render() {\r\n      if(this.state.hasError) {\r\n          return <div>Something went wrong</div>;\r\n      }\r\n\r\n      return this.props.children;\r\n  }\r\n}\r\n"]},"metadata":{},"sourceType":"module"}